[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.54.0"
glam = "0.29.2"
itertools = "0.13.0"
nom = "7.1.3"
nom_locate = "4.2.0"
rayon = "1.10.0"
regex = "1.11.1"
serde = "1.0.215"
serde_scan = "0.4.1"
